# .github/workflows/pages.yml
name: CI & Deploy to Cloudflare Pages

# ────────────────────────────────
# Triggers
#   • Production deploys on pushes to main
#   • Preview environments on pull‑requests to main
# ────────────────────────────────
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest
    timeout-minutes: 30 # fail‑fast safety

    # Abort superseded runs (e.g. force‑pushes)
    concurrency:
      group: pages-${{ github.head_ref || github.ref }}
      cancel-in-progress: true

    # Minimal permissions for secure deployments
    permissions:
      contents: read
      deployments: write

    steps:
      # ——— Check out repo —————————————————————————————————————
      - name: 🛎️ Checkout
        uses: actions/checkout@v4

      # ——— Toolchain setup ————————————————————————————————
      - name: 🔧 Setup Node .js
        uses: actions/setup-node@v4
        with:
          node-version: 20 # active LTS
          cache: npm # automatic npm cache

      # ——— Install, test, lint ——————————————————————————————
      - name: 📥 Install dependencies
        run: npm ci

      - name: 🧹 Lint
        run: npm run lint

      # If you have tests, uncomment the block below
      # - name: 🧪 Test
      #   run: npm test --if-present

      # ——— Build Astro for Pages ————————————————————————————
      - name: 🏗️ Build site
        run: npm run build # runs `astro build` → ./dist

      # ——— Install Wrangler globally first ——————————————————
      - name: 🧰 Install Wrangler
        run: npm install -g wrangler@latest

      # ——— Deploy with Wrangler CLI directly ————————————————
      - name: 🚀 Deploy to Cloudflare Pages
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          NODE_VERSION: 20
        run: wrangler pages deploy dist --project-name=personal-website --branch=${{ github.ref_name }}
